language: node_js
node_js:
  - 14
sudo: false
dist: trusty
addons:
  chrome: stable
install:
  - npm i -g npm@latest
  - npm install codecov -g
  - npm ci
script:
  - npm test
after_success:
  - npm run coverage
